version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"

conda:
  environment: docs/build-environment.yml

sphinx:
  # Path to Sphinx configuration file
  configuration: docs/conf.py
