name: xeus-python-wasm-build
channels:
  - https://prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - cmake
  - emscripten_emscripten-wasm32
  - pip
  - python=3.13
  - yarn
  - click
  # JupyterLite
  - jupyterlite-core >0.6
  - jupyter_server
  - jupyterlite-xeus
  - # widgets
  - ipywidgets